/**
 * Agape — SVGO configuration
 *
 * Per DESIGN.md §3.5.1.8.4, every SVG in public/brand/ MUST be optimized
 * through this config before commit. The output is reproducible (committed
 * config), so `npx svgo public/brand/*.svg` produces identical results
 * locally and in CI.
 *
 * What this preserves:
 *   - viewBox / role="img" / aria-label
 *   - fill colors (so monochrome variants generated by sed/awk still
 *     render correctly)
 *
 * What this strips:
 *   - editor metadata (Adobe Illustrator namespaces, Inkscape IDs)
 *   - comments
 *   - empty groups / unused defs
 *   - precision beyond 1 decimal (visually lossless at 64px-1280px)
 *
 * What this does NOT touch:
 *   - <text> content — the dev must outline text per §3.5.1.8.3 BEFORE
 *     running svgo. svgo does not convert text to paths.
 *
 * Verification per §3.5.1.8.5: each output file must measure ≤ 2048 bytes
 * (CI check via `wc -c` per Appendix C item 23).
 *
 * svgo v4 syntax: `removeViewBox` is no longer an override of
 * preset-default — it's a top-level plugin. We add it after
 * preset-default with `params: false` to keep the viewBox intact
 * (Logo.astro relies on it to scale via the size prop).
 */
export default {
  multipass: true,
  js2svg: {
    indent: 2,
    pretty: false,           // minified output for size
  },
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          // Keep IDs that might be referenced by other elements
          cleanupIds: { minify: false },
          // 1-decimal precision — visually lossless at the 64-1280px
          // display range, and keeps the dove + ring trace under the
          // §3.5.1.8.5 strict ceiling of 2,048 bytes. 2 decimals is
          // indistinguishable at any practical zoom level but doubles
          // the path-data byte count; 0 decimals causes the long
          // curved runs on the dove's wing + tail to show as visible
          // faceting.
          cleanupNumericValues: { floatPrecision: 1 },
          // Bake transforms into path coords (smaller + faster to render).
          convertPathData: { transformPrecision: 1, floatPrecision: 1 },
        },
      },
    },
    'removeDimensions',     // forces consumers to size via width/height attributes
    'sortAttrs',
    {
      name: 'removeViewBox',
      params: false,         // keep viewBox — Logo.astro needs it
    },
  ],
};
