/**
 * Agape — SVGO configuration
 *
 * Per DESIGN.md §3.5.1.8.4, every SVG in public/brand/ MUST be optimized
 * through this config before commit. The output is reproducible (committed
 * config), so `npx svgo public/brand/*.svg` produces identical results
 * locally and in CI.
 *
 * What this preserves:
 *   - viewBox / role="img" / aria-label
 *   - fill colors (so monochrome variants generated by sed/awk still
 *     render correctly)
 *
 * What this strips:
 *   - editor metadata (Adobe Illustrator namespaces, Inkscape IDs)
 *   - comments
 *   - empty groups / unused defs
 *   - precision beyond 1 decimal (visually lossless at 64px-1280px)
 *
 * What this does NOT touch:
 *   - <text> content — the dev must outline text per §3.5.1.8.3 BEFORE
 *     running svgo. svgo does not convert text to paths.
 *
 * Verification per §3.5.1.8.5: each output file must measure ≤ 2048 bytes
 * (CI check via `wc -c` per Appendix C item 23).
 */
export default {
  multipass: true,
  js2svg: {
    indent: 2,
    pretty: false,           // minified output for size
  },
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          // Keep viewBox (so the Logo.astro size prop scales correctly)
          removeViewBox: false,
          // Keep IDs that might be referenced by other elements
          cleanupIds: { minify: false },
        },
      },
    },
    'removeDimensions',     // forces consumers to size via width/height attributes
    'sortAttrs',
  ],
};
